### ISSUE TITLE
Pounce

### ISSUE THREAD

**Issue by fredrikwidlund** [denji/awesome-http-benchmark#24]
https://github.com/fredrikwidlund/pounce is a new version of my old "pounce" project that is currently in the list.

Kind regards,
Fredrik

**Comment by fredrikwidlund** [comment]
Thanks. As a side note it just shares the name with the previous project, no code is shared and this version is built on my libreactor project. The ambition is to be similar in shape to wrk, but with lower latency (for the same load) and higher throughput, however whether this is true in real life is not for me to decide. Regardless the current description is likely (or hopefully) not true.

Kind regards,
Fredrik

**Comment by denji** [comment]
Any corrections to the README.md are welcome via pull request :)

**Comment by fredrikwidlund** [comment]
Yes, I will try to write something as objective as possible then. :)
